version: '3'

services:
  db:
    container_name: postgres_database
    image: postgres:15.1
    volumes:
      # - postgres-db:/var/lib/postgresql/data
      - ./postgres/:/var/lib/postgresql/data # Bind Volume: apunta hacia un proyecto en el host
    environment:
      - POSTGRES_PASSWORD=123456

  pgAdmin:
    depends_on:
      #Depende de que la base de datos este levantada
      - db #se debe de poner el nombre del servicio no el nombre del contenedor
    image: dpage/pgadmin4:6.17
    ports:
      - 8080:80
    volumes:
      - ./pgAdmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com

# Crear un nuevo volumen con el nombre postgres-db
# volumes: 
#   postgres-db:

volumes:
  postgres-db:
    external: true # Con esta linea se toma el volumen ya creado
