version: '3.9'
services:
    backend:
        build:
            context: .
            dockerfile: php.Dockerfile
        container_name: backend_svc
        ports:
            - 8080:80
        volumes:
            - '/Users/kenneturrutia/Desktop/Docker_Docker-Compose/www/:/var/www/html'
        depends_on: # Se levanta unicamente si ya esta levantada la base de datos
            - database
        networks:
            app_network:
                aliases:
                - backend_host
    database:
        build:
            context: .
            dockerfile: mariadb.Dockerfile
        container_name: mariadb_svc
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: 'custom_db'
            MYSQL_ROOT_PASSWORD: 'customPassword123$'
        volumes:
            - '/Users/kenneturrutia/Desktop/Docker_Docker-Compose/schemas/:/var/lib/mysql'
        networks:
            app_network:
                aliases:
                - mariadb_host
volumes:
    www: {}
    shemas: {}

networks:
    app_network:
        name: app_net
        driver: bridge
        ipam:
            driver: default
