FROM nginx:alpine
# RUN echo "hola mundo"

ARG MyArgumento="Soy un argumento" #Se toma este valor si no se ha definido ninguno en el docker-compose.yml

RUN echo "Hola soy ${MyArgumento}"

# CMD ["echo", "mensaje creado desde dockerfile nuevo"]